[graph]
all-features = false
no-default-features = false


[output]
feature-depth = 1


[advisories]
ignore = [ "RUSTSEC-2023-0071" ]


[licenses]
allow = [
"Apache-2.0",
"MIT",
"BSD-3-Clause",
"Zlib",
"ISC",
"Unicode-3.0",
"CDLA-Permissive-2.0"
]
confidence-threshold = 0.9
exceptions = [ ]


[licenses.private]
ignore = true
registries = [ ]


[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = [ ]
deny = [ ]
skip = [ ]
skip-tree = [ ]


[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [ "https://github.com/rust-lang/crates.io-index" ]
allow-git = [
"https://github.com/eclipse-opensovd/classic-diagnostic-adapter.git",
"https://github.com/alexmohr/aide.git",
"https://github.com/alexmohr/flatbuffers.git"
]


[sources.allow-org]
github = [ ]
gitlab = [ ]
bitbucket = [ ]
